Repository navcoin/navcoin-core, pull requests merged in 2019-08, with the labels that each got.

#582 Updated a lock on LoadWallet to fix a crash on wallet rescan (Existin…
  src/wallet/walletdb.cpp
Labels: needed for final release, ready for review

#523 Coldstaking pool fee
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/coldstaking_fee.py
  src/chainparams.cpp
  src/consensus/params.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/transactionrecord.cpp
  src/rpc/blockchain.cpp
  src/versionbits.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: needed for final release, ready for review

#589 OSX pink menu bug
  .gitignore
  src/qt/navcoingui.cpp
  src/qt/res/icons/community_fund_hover.png
  src/qt/res/icons/community_fund_ns.png
  src/qt/res/icons/community_fund_s.png
  src/qt/res/icons/home_hover.png
  src/qt/res/icons/home_ns.png
  src/qt/res/icons/home_s.png
  src/qt/res/icons/logo_ns.png
  src/qt/res/icons/receive_hover.png
  src/qt/res/icons/receive_ns.png
  src/qt/res/icons/receive_s.png
  src/qt/res/icons/send_hover.png
  src/qt/res/icons/send_ns.png
  src/qt/res/icons/send_s.png
  src/qt/res/icons/transaction_hover.png
  src/qt/res/icons/transaction_ns.png
  src/qt/res/icons/transaction_s.png
Labels: needed for final release

#590 Fix to staking parameter "-mininputvalue"
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/staking_mininputvalue.py
  src/wallet/wallet.cpp
Labels: bounty-low
