Repository navcoin/navcoin-core, pull requests merged in 2019-06, with the labels that each got.

#480 Fix RPC Tests
  qa/rpc-tests/cfund-rawtx-create-proposal.py
  src/chainparams.cpp
Labels: ready for review

#507 Fixed a bug with the errorLogFile causing crashes
  src/qt/rpcconsole.cpp
Labels: needed for final release, work in progress

#505 Prevent segfault on gui close
  src/qt/rpcconsole.cpp
Labels: needed for final release, ready for review

#504 default .conf
  src/qt/intro.cpp
  src/qt/intro.h
Labels: bounty pending payment, bounty-low

#512 Remove Bootstrap option from GUI
  src/qt/navcoingui.cpp
  src/qt/navcoingui.h
Labels: ready for review

#494 Use -rescan when -importmnemonic
  qa/rpc-tests/mnemonic.py
  src/init.cpp
Labels: needed for final release, ready for review

#506 Fix potential deadlock
  src/main.cpp
Labels: needed for final release, ready for review

#469 Added some new FIAT currencies and enabled auto price update (Default value 300K ms)
  src/qt/forms/optionsdialog.ui
  src/qt/guiconstants.h
  src/qt/navcoingui.cpp
  src/qt/navcoingui.h
  src/qt/navcoinunits.cpp
  src/qt/navcoinunits.h
  src/util.h
Labels: bounty-med, ready for review

#484 Moved the checkboxes into the empty QGroupBox
  src/qt/forms/optionsdialog.ui
Labels: ready for review

#514 [OSX] macdeployqtplus bug fixes [OSX]
  Makefile.am
  configure.ac
  contrib/macdeploy/background.svg
  contrib/macdeploy/background.tiff
  contrib/macdeploy/background.tiff.png
  contrib/macdeploy/background.tiff@2x.png
  contrib/macdeploy/custom_dsstore.py
  contrib/macdeploy/macdeployqtplus
Labels: bounty-low, ready for review

#485 Added new attributes to the `getstakinginfo` and `getstakereport` commands
  qa/rpc-tests/getstakereport.py
  qa/rpc-tests/getstakinginfo.py
  src/rpc/net.cpp
  src/wallet/rpcwallet.cpp
Labels: ready for review

#526 Added new progress ui for sync
  src/Makefile.qt.include
  src/main.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/forms/modaloverlay.ui
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/modaloverlay.cpp
  src/qt/modaloverlay.h
  src/qt/navcoingui.cpp
  src/qt/navcoingui.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: bounty-high, ready for review

#537 Make some tests more reliable
  qa/rpc-tests/cfund-proposal-state-accept.py
  qa/rpc-tests/coldstaking_spending.py
Labels: ready for review

#533 Fixed some file permissions
  src/qt/forms/addressbookpage.ui
  src/qt/forms/askpassphrasedialog.ui
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/debugwindow.ui
  src/qt/forms/editaddressdialog.ui
  src/qt/forms/helpmessagedialog.ui
  src/qt/forms/intro.ui
  src/qt/forms/openuridialog.ui
  src/qt/forms/optionsdialog.ui
  src/qt/forms/overviewpage.ui
  src/qt/forms/receivecoinsdialog.ui
  src/qt/forms/receiverequestdialog.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/forms/sendcoinsentry.ui
  src/qt/forms/signverifymessagedialog.ui
  src/qt/forms/transactiondescdialog.ui
Labels: ready for review

#517 Move nBits check to ContextualCheckBlock
  src/main.cpp
Labels: blockchain, needed for final release, ready for review

#532 Updated the error log tab logic
  src/qt/rpcconsole.cpp
  src/util.cpp
Labels: bounty pending payment, bounty-low, needed for final release, ready for review

#536 Check node address in header spam protection
  src/init.cpp
  src/main.cpp
  src/main.h
Labels: needed for final release, ready for review

#544 Revert nBits patch
  src/main.cpp
Labels: needed for final release, ready for review
