Repository navcoin/navcoin-core, pull requests merged in 2019-07, with the labels that each got.

#553 Removed unused variable nLength
  src/qt/sendcoinsdialog.cpp
Labels: ready for review

#549 Updated __poll_chk implementation to be not so strict
  src/compat/glibc_compat.cpp
Labels: needed for final release, ready for review

#558 Added an additional LOCK for cs_main
  src/qt/communityfunddisplay.cpp
  src/wallet/rpcwallet.cpp
Labels: needed for final release, ready for review

#555 Added -print flag as alias to -printtoconsole
  src/init.cpp
Labels: ready for review

#562 new SVG icons
  src/qt/res/icons/vector/about.svg
  src/qt/res/icons/vector/add.svg
  src/qt/res/icons/vector/address-book.svg
  src/qt/res/icons/vector/chevron.svg
  src/qt/res/icons/vector/clock1.svg
  src/qt/res/icons/vector/clock2.svg
  src/qt/res/icons/vector/clock3.svg
  src/qt/res/icons/vector/clock4.svg
  src/qt/res/icons/vector/clock5.svg
  src/qt/res/icons/vector/configure.svg
  src/qt/res/icons/vector/connect0.svg
  src/qt/res/icons/vector/connect1.svg
  src/qt/res/icons/vector/connect2.svg
  src/qt/res/icons/vector/connect3.svg
  src/qt/res/icons/vector/connect4.svg
  src/qt/res/icons/vector/debugwindow.svg
  src/qt/res/icons/vector/edit.svg
  src/qt/res/icons/vector/editcopy.svg
  src/qt/res/icons/vector/editpaste.svg
  src/qt/res/icons/vector/export.svg
  src/qt/res/icons/vector/eye.svg
  src/qt/res/icons/vector/eye_minus.svg
  src/qt/res/icons/vector/eye_plus.svg
  src/qt/res/icons/vector/filesave.svg
  src/qt/res/icons/vector/fontbigger.svg
  src/qt/res/icons/vector/fontsmaller.svg
  src/qt/res/icons/vector/ghost.svg
  src/qt/res/icons/vector/history.svg
  src/qt/res/icons/vector/info.svg
  src/qt/res/icons/vector/key.svg
  src/qt/res/icons/vector/lock_closed.svg
  src/qt/res/icons/vector/lock_open.svg
  src/qt/res/icons/vector/open.svg
  src/qt/res/icons/vector/overview.svg
  src/qt/res/icons/vector/quit.svg
  src/qt/res/icons/vector/receive.svg
  src/qt/res/icons/vector/remove.svg
  src/qt/res/icons/vector/send.svg
  src/qt/res/icons/vector/staking_off.svg
  src/qt/res/icons/vector/staking_on.svg
  src/qt/res/icons/vector/synced.svg
  src/qt/res/icons/vector/transaction0.svg
  src/qt/res/icons/vector/transaction2.svg
  src/qt/res/icons/vector/transaction_abandonded.svg
  src/qt/res/icons/vector/transaction_conflicted.svg
  src/qt/res/icons/vector/tx_inout.svg
  src/qt/res/icons/vector/tx_input.svg
  src/qt/res/icons/vector/tx_mined.svg
  src/qt/res/icons/vector/tx_output.svg
  src/qt/res/icons/vector/verify.svg
  src/qt/res/icons/vector/warning.svg
Labels: bounty pending payment, bounty-med

#564 Added a lock before we call GetTxStakeAmount()
  src/wallet/rpcwallet.cpp
Labels: needed for final release, ready for review

#575 vector logo and icon
  src/qt/res/icons/Icon.svg
  src/qt/res/icons/logo.svg
Labels: bounty-med

#571 Fixed crash when selecting a currency with no price data
  src/qt/navcoinunits.cpp
Labels: needed for final release, ready for review

#511 Added FAILFAST for functional test suite
  .travis/test_06_script_b.sh
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/test_framework/test_framework.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/wallet-hd.py
Labels: ready for review

#551 Updated the sendcoinsdialog pop up display currencies text
  src/qt/sendcoinsdialog.cpp
Labels: bounty-low, ready for review

#577 [cfund] Added a lock (Crashed the wallet when voting from details dialog)
  src/qt/communityfunddisplaydetailed.cpp
Labels: needed for final release, ready for review
