Repository navcoin/navcoin-core, pull requests merged in 2019-10, with the labels that each got.

#605 Staking reward setup GUI
  src/Makefile.qt.include
  src/qt/forms/overviewpage.ui
  src/qt/navcoingui.cpp
  src/qt/navcoingui.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/qjsonitem.cpp
  src/qt/qjsonitem.h
  src/qt/qjsonmodel.cpp
  src/qt/qjsonmodel.h
  src/qt/qt_libnavcoinqt_a-moc_walletview-fcb89852.o.tmp
  src/qt/splitrewards.cpp
  src/qt/splitrewards.h
  src/qt/transactionrecord.cpp
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: needed for final release, ready for review

#603 Updated depends to use winssl for windows and darwinssl for osx
  depends/packages/curl.mk
  depends/patches/curl/fix_lib_order.patch
Labels: needed for final release, ready for review

#587 Add support for raw script addresses
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/createrawscriptaddress.py
  src/base58.cpp
  src/base58.h
  src/chainparams.cpp
  src/chainparams.h
  src/script/standard.cpp
  src/script/standard.h
  src/wallet/rpcwallet.cpp
Labels: needed for final release, ready for review

#554 Replaced Q_FOREACH with for() from c++11 standard
  src/qt/addressbookpage.cpp
  src/qt/coincontroldialog.cpp
  src/qt/navcoingui.cpp
  src/qt/optionsdialog.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/platformstyle.cpp
  src/qt/receivecoinsdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/test/paymentservertests.cpp
  src/qt/trafficgraphwidget.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/utilitydialog.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodeltransaction.cpp
Labels: ready for review, refactor

#561 Fixed gitignore permissions and added new file to main gitignore
  .gitignore
  depends/.gitignore
  qa/rpc-tests/.gitignore
  src/bench/.gitignore
  src/leveldb/.gitignore
  src/obj-test/.gitignore
  src/obj/.gitignore
Labels: ready for review

#608 Fix CFund DB read after nullified entry
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/cfund-reorg.py
  src/coins.cpp
  src/consensus/cfund.cpp
  src/main.cpp
Labels: needed for final release, ready for review

#611 Fixed error.log loading in Debug Window (Windows)
  src/qt/rpcconsole.cpp
Labels: needed for final release, ready for review

#546 Added new -allindex option
  src/init.cpp
  src/main.cpp
Labels: ready for review

#614 Patch for staking redirect gui
  src/qt/splitrewards.cpp
Labels: needed for final release, ready for review

#615 Bump version number
  configure.ac
  doc/Doxyfile
  src/clientversion.h
Labels: needed for final release, ready for review

#527 Updated the custom 'change' address to be a persistent setting
  src/qt/sendcoinsdialog.cpp
Labels: bounty pending payment, bounty-low, ready for review

#616 Added release notes
  doc/release-notes/release-notes-4.7.0.md
  doc/release-notes/release-notes-4.7.1.md
Labels: needed for final release, ready for review
