Repository navcoin/navcoin-core, pull requests merged in 2019-05, with the labels that each got.

#459 Missing increased buffer for cfund gui
  src/qt/communityfunddisplay.cpp
Labels: needed for final release

#450 This PR is a combined fix for issues #445 and #446
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/coldstaking_spending.py
  qa/rpc-tests/getstakereport.py
  qa/rpc-tests/mempool_spendcoinbase.py
  qa/rpc-tests/sendtoaddress.py
  qa/rpc-tests/stakeimmaturebalance.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/wallet.py
  src/chainparams.cpp
  src/consensus/consensus.h
  src/consensus/params.h
  src/main.cpp
  src/main.h
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/test/test_navcoin.cpp
  src/txmempool.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: needed for final release

#456 Fix for Payment Request reorganizations
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/cfund-paymentrequest-extract-funds.py
  qa/rpc-tests/cfund-paymentrequest-state-reorg.py
  qa/rpc-tests/cfund-rawtx-paymentrequest-create.py
  src/consensus/cfund.cpp
  src/consensus/cfund.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/communityfundcreatepaymentrequestdialog.cpp
  src/qt/communityfunddisplay.cpp
  src/qt/communityfunddisplaydetailed.cpp
  src/qt/communityfunddisplaypaymentrequest.cpp
  src/qt/communityfunddisplaypaymentrequestdetailed.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: needed for final release

#444 v4.6.0 rc
  README.md
  configure.ac
  doc/Doxyfile
  doc/README.md
  doc/README_windows.txt
  doc/release-notes/release-notes-4.6.0.md
Labels: needed for final release

#474 Added password prompt for CFund payment/proposal dialogs
  src/qt/communityfundcreatepaymentrequestdialog.cpp
  src/qt/communityfundcreatepaymentrequestdialog.h
  src/qt/communityfundcreateproposaldialog.cpp
  src/qt/communityfundcreateproposaldialog.h
  src/qt/communityfundpage.cpp
Labels: bounty-low

#472 Added new details for getstakinginfo error message as suggested in #288
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/getstakinginfo.py
  src/main.cpp
  src/main.h
  src/rpc/net.cpp
Labels: bounty-low

#489 Updated the navcoin.ico file to use new art :D
  src/qt/icons/navcoin.ico
Labels: ready for review

#492 Updated other ico files as well (missed them on the first PR #489)
  share/pixmaps/navcoin.ico
  src/Makefile.qt.include
  src/icons/navcoin.ico
  src/qt/res/icons/navcoin.ico
  src/qt/res/icons/navcoin.png
  src/qt/res/icons/navcoin_testnet.ico
  src/qt/res/navcoin-qt-res.rc
Labels: ready for review

#479 Fix for importaddress returning incorrect amounts
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/importaddress.py
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/script/ismine.cpp
  src/wallet/rpcdump.cpp
Labels: bounty pending payment, bounty-med, work in progress

#487 Use of the CoinsDB for the Community Fund
  .gitignore
  qa/rpc-tests/cfund-paymentrequest-state-accept-expired-proposal.py
  qa/rpc-tests/cfund-vote.py
  src/coins.cpp
  src/coins.h
  src/consensus/cfund.cpp
  src/consensus/cfund.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/communityfundcreatepaymentrequestdialog.cpp
  src/qt/communityfunddisplay.cpp
  src/qt/communityfunddisplaydetailed.cpp
  src/qt/communityfunddisplaypaymentrequest.cpp
  src/qt/communityfunddisplaypaymentrequestdetailed.cpp
  src/qt/communityfundpage.cpp
  src/qt/navcoingui.cpp
  src/rpc/blockchain.cpp
  src/test/coins_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/txmempool.cpp
  src/txmempool.h
  src/wallet/rpcwallet.cpp
Labels: ready for review, testing needed

#466 Added error log tab in debug window
  depends/packages/qt.mk
  src/init.cpp
  src/qt/forms/debugwindow.ui
  src/qt/guiconstants.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/util.cpp
  src/util.h
Labels: bounty-med, ready for review
