Repository navcoin/navcoin-core, pull requests merged in 2021-01, with the labels that each got.

#749 [FIX] Use mainnet by default when release candidate is no test release
  src/chainparamsbase.cpp
  src/main.cpp
  src/wallet/wallet.cpp
Labels: ready for review

#750 Fixed a crash caused by system tray icon not being available
  src/qt/navcoingui.cpp
Labels: bug, gui, ready for review

#751 Added tilde (~) support to the datadir param for navcoin
  src/util.cpp
Labels: enhancement, ready for review, wallet

#752 Fixed the missing transaction size in send coins dialog
  src/qt/walletmodel.cpp
  src/qt/walletmodeltransaction.cpp
  src/qt/walletmodeltransaction.h
Labels: bug, gui, ready for review, wallet

#753 update blsct key generation warning message
  src/wallet/wallet.cpp
Labels: ready for review, wallet

#754 Update copyright years
  configure.ac
  src/chainparams.cpp
  src/clientversion.h
  src/coins.cpp
  src/consensus/dao.cpp
  src/consensus/dao.h
  src/consensus/dao/flags.h
  src/consensus/daoconsensusparams.h
  src/daoversionbit.cpp
  src/daoversionbit.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/miner.h
  src/pos.cpp
  src/pos.h
  src/qt/daoconsultationcreate.cpp
  src/qt/daoconsultationcreate.h
  src/qt/daoconsultationvote.cpp
  src/qt/daoconsultationvote.h
  src/qt/daopage.cpp
  src/qt/daopage.h
  src/qt/daoproposeanswer.cpp
  src/qt/daoproposeanswer.h
  src/qt/daosupport.cpp
  src/qt/daosupport.h
  src/qt/navcoinlistwidget.cpp
  src/qt/navcoinlistwidget.h
  src/qt/navcoinpushbutton.cpp
  src/qt/navcoinpushbutton.h
  src/qt/splitrewards.cpp
  src/qt/splitrewards.h
  src/qt/styles/dark.cpp
  src/qt/styles/dark.h
  src/qt/styles/light.cpp
  src/qt/styles/light.h
  src/rpc/mining.cpp
  src/test/cfund_tests.cpp
  src/test/cfunddb_tests.cpp
Labels: ready for review

#756 Fixes #755
  src/rpc/blockchain.cpp
Labels: ready for review

#761 Fix for a wallet crash related to encryption detection
  src/util.cpp
Labels: ready for review

#758 Final version 6.0
  configure.ac
  src/clientversion.h
Labels: ready for review

#757 Add codesign to gitian
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/macdeploy/detached-sig-apply.sh
  contrib/macdeploy/detached-sig-create.sh
  doc/release-process.md
Labels: ready for review

#760 Update release notes doc 6.0
  doc/release-notes/release-notes-6.0.md
Labels: ready for review
