Repository navcoin/navcoin-core, pull requests merged in 2021-11, with the labels that each got.

#863 Replaced boost::filesystem with fs:: from upstream code changes
  src/Makefile.am
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/fs.cpp
  src/fs.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/navcoin-cli.cpp
  src/navcoind.cpp
  src/net.cpp
  src/net.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/navcoin.cpp
  src/rpc/protocol.cpp
  src/rpc/protocol.h
  src/rpc/server.cpp
  src/test/test_navcoin.cpp
  src/test/test_navcoin.h
  src/test/testutil.cpp
  src/test/testutil.h
  src/untar.cpp
  src/util.cpp
  src/util.h
  src/utils/dns_utils.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: ready for review

#866 Updated the build aux pthread file
  Makefile.am
  build-aux/m4/ax_pthread.m4
  configure.ac
  src/Makefile.am
Labels: ready for review

#869 Updated univalue based on upstream changes
  src/univalue/Makefile.am
  src/univalue/README.md
  src/univalue/configure~
  src/univalue/include/univalue.h
  src/univalue/lib/univalue_get.cpp
  src/univalue/lib/univalue_read.cpp
  src/univalue/test/fail45.json
  src/univalue/test/object.cpp
  src/univalue/test/pass4.json
  src/univalue/test/unitester.cpp
Labels: ready for review

#856 DAO protocol upgrade
  contrib/stressor_dao.sh
  src/bls/build/.empty
  src/bls/build/.gitkeep
  src/chainparams.cpp
  src/consensus/dao.cpp
  src/consensus/dao.h
  src/consensus/params.h
  src/main.cpp
  src/main.h
  src/qt/communityfundcreatepaymentrequestdialog.cpp
  src/qt/communityfundcreateproposaldialog.cpp
  src/qt/daopage.cpp
  src/qt/forms/communityfundcreateproposaldialog.ui
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/versionbits.h
  src/wallet/rpcwallet.cpp
Labels: ready for review

#867 Add asm support in configure.ac and updated crc32c based on upstream changes
  configure.ac
  src/Makefile.crc32c.include
  src/crc32c/.appveyor.yml
  src/crc32c/.travis.yml
  src/crc32c/.ycm_extra_conf.py
  src/crc32c/AUTHORS
  src/crc32c/CMakeLists.txt
  src/crc32c/Crc32cConfig.cmake.in
  src/crc32c/README.md
  src/crc32c/src/crc32c.cc
  src/crc32c/src/crc32c_arm64.cc
  src/crc32c/src/crc32c_arm64.h
  src/crc32c/src/crc32c_arm64_check.h
  src/crc32c/src/crc32c_benchmark.cc
  src/crc32c/src/crc32c_read_le.h
Labels: ready for review

#862 xNAV upgrades for Navcoin Core 7.0.0
  contrib/stressor_token.sh
  src/Makefile.am
  src/amount.h
  src/bls/src/elements.cpp
  src/bls/src/elements.hpp
  src/blsct/aggregationsession.cpp
  src/blsct/aggregationsession.h
  src/blsct/bulletproofs.cpp
  src/blsct/bulletproofs.h
  src/blsct/transaction.cpp
  src/blsct/transaction.h
  src/blsct/verification.cpp
  src/chainparams.cpp
  src/coins.cpp
  src/coins.h
  src/compressor.h
  src/consensus/daoconsensusparams.h
  src/consensus/params.h
  src/consensus/program_actions.h
  src/consensus/programs.h
  src/ctokens/ctokens.h
  src/ctokens/tokenid.h
  src/init.cpp
  src/keystore.cpp
  src/keystore.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/ntpclient.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/random.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
  src/script/script.h
  src/serialize.h
  src/test/rpc_tests.cpp
  src/test/versionbits_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/txmempool.cpp
  src/txmempool.h
  src/versionbits.cpp
  src/versionbits.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: ready for review

#873 Updated splash screen logo to work better with the dark theme
  src/qt/res/icons/logo_n.png
  src/qt/res/icons/logo_n.svg
  src/qt/res/icons/navcoin.icns
  src/qt/res/icons/navcoin.ico
  src/qt/res/icons/navcoin.png
  src/qt/res/icons/navcoin.svg
  src/qt/res/icons/navcoin_full.png
  src/qt/res/icons/navcoin_full.svg
Labels: ready for review

#878 Bump version to 7.0.0
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  doc/Doxyfile
  src/chainparams.cpp
  src/clientversion.h
Labels: ready for review

#872 Updated to use c++17
  configure.ac
  src/bls/CMakeLists.txt
  src/bls/src/CMakeLists.txt
  src/bls/src/elements.hpp
  src/bls/src/privatekey.cpp
  src/bls/src/util.hpp
  src/random.h
Labels: ready for review

#881 Removed error about NTP min measures value from stressor
  contrib/stressor_dao.sh
Labels: ready for review

#875 Added --enable-suppress-external-warnings flag support from upstream
  configure.ac
Labels: ready for review

#874 Updated depends libsodium to use variables for AR, RANLIB
  depends/packages/sodium.mk
Labels: ready for review

#877 dotNAV
  contrib/stressor_dotnav.sh
  src/Makefile.am
  src/blsct/key.h
  src/blsct/verification.cpp
  src/blsct/verification.h
  src/chainparams.cpp
  src/coins.cpp
  src/coins.h
  src/consensus/daoconsensusparams.h
  src/consensus/params.h
  src/consensus/program_actions.h
  src/consensus/programs.cpp
  src/consensus/programs.h
  src/dotnav/namedata.h
  src/dotnav/namerecord.h
  src/dotnav/names.cpp
  src/dotnav/names.h
  src/main.cpp
  src/main.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/blockchain.cpp
  src/serialize.h
  src/txdb.cpp
  src/txdb.h
  src/txmempool.cpp
  src/txmempool.h
  src/uint256.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: ready for review

#879 Release notes v7.0.0
  doc/release-notes/release-notes-7.0.0.md
Labels: ready for review

#880 Fixed a bug that caused the dark theme splash screen to look white
  src/qt/res/themes/light/styles.qss
  src/qt/splashscreen.cpp
Labels: bug, gui, ready for review

#884 Replaced some BITCOIN_* header comments and defines with NAVCOIN_*
  src/crypto/chacha20.h
  src/crypto/external/hmac_sha256.h
  src/crypto/external/hmac_sha512.h
  src/crypto/external/pkcs5_pbkdf2.h
  src/crypto/external/sha256.h
  src/crypto/external/sha512.h
  src/crypto/external/zeroize.h
  src/key.h
  src/key_io.h
  src/script/sign.h
  src/univalue/gen/gen.cpp
  src/univalue/lib/univalue_escapes.h
Labels: ready for review

#885 Updated gitian to use focal instead of bionic
  configure.ac
  contrib/devtools/security-check.py
  contrib/devtools/symbol-check.py
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  src/Makefile.am
  src/compat/glibc_compat.cpp
Labels: ready for review

#887 Added glibc compat for fcntl and fcntl64
  configure.ac
  src/compat/glibc_compat.cpp
Labels: ready for review

#882 GUI for combined consensus feature
  src/consensus/dao.cpp
  src/consensus/daoconsensusparams.h
  src/qt/daoconsultationvote.cpp
  src/qt/daosupport.cpp
Labels: gui, ready for review

#888 Added upstream hardening changes (Fix for failing security check on gitian build)
  configure.ac
Labels: ready for review

#892 Updated the .editorconfig file to use 2 space tabs for .mk and .ac files
  .editorconfig
Labels: ready for review

#883 Removed some old logs that are no longer needed (CDB related logs)
  src/wallet/db.cpp
Labels: ready for review

#895 Fix rpc help command
  src/wallet/rpcwallet.cpp
Labels: ready for review
