Repository navcoin/navcoin-core, pull requests merged in 2022-01, with the labels that each got.

#906 Fix xNAV to NAV from the new NavCash
  src/wallet/wallet.cpp
Labels: ready for review

#912 [FIX] Generate random key if not viewing key available
  src/main.cpp
Labels: ready for review

#905 Updated c++std for bdb, boost, qt and zeromq
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/qt.mk
  depends/packages/zeromq.mk
Labels: ready for review

#915 Fix for #914 GUI crash when no system notificator is available
  src/qt/navcoingui.cpp
Labels: bug, ready for review

#908 Removed trailing whitespace in `.cpp` and `.h` files in `./src`
  src/addrman.cpp
  src/addrman.h
  src/bloom.h
  src/blsct/bulletproofs.cpp
  src/crypto/external/hmac_sha256.h
  src/crypto/external/hmac_sha512.h
  src/crypto/external/sha256.h
  src/crypto/external/sha512.h
  src/crypto/external/zeroize.h
  src/main.cpp
  src/mcl/sample/bench.cpp
  src/mnemonic/dictionary.cpp
  src/primitives/block.cpp
  src/pubkey.h
  src/qt/optionsdialog.cpp
  src/qt/qvalidatedlineedit.h
  src/sph_blake.h
  src/sph_bmw.h
  src/sph_cubehash.h
  src/sph_echo.h
  src/sph_fugue.h
  src/sph_groestl.h
  src/sph_hamsi.h
  src/sph_jh.h
  src/sph_keccak.h
  src/sph_luffa.h
  src/sph_shavite.h
  src/sph_simd.h
  src/sph_skein.h
  src/sph_types.h
  src/streams.h
  src/test/limitedmap_tests.cpp
  src/test/mempool_tests.cpp
  src/timedata.h
  src/undo.h
Labels: ready for review

#916 Add resolvename subdomains
  src/dotnav/names.cpp
  src/dotnav/names.h
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: ready for review, rpc
